# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: navigator_eventbus/ingress/proto/events.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'navigator_eventbus/ingress/proto/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-navigator_eventbus/ingress/proto/events.proto\x12\x10parrot.events.v1\"\x8e\x02\n\x0ePublishRequest\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x14\n\x0cpayload_json\x18\x03 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x12\x0e\n\x06source\x18\x06 \x01(\t\x12\x15\n\x08severity\x18\x07 \x01(\x05H\x00\x88\x01\x01\x12\x15\n\x08priority\x18\x08 \x01(\x05H\x01\x88\x01\x01\x12\x16\n\x0e\x63orrelation_id\x18\t \x01(\t\x12\x15\n\rmetadata_json\x18\n \x01(\t\x12\x1a\n\x12trace_context_json\x18\x0b \x01(\tB\x0b\n\t_severityB\x0b\n\t_priority\"S\n\x0fPublishResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08\x65vent_id\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t2a\n\x0f\x45ventBusIngress\x12N\n\x07Publish\x12 .parrot.events.v1.PublishRequest\x1a!.parrot.events.v1.PublishResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'navigator_eventbus.ingress.proto.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUBLISHREQUEST']._serialized_start=68
  _globals['_PUBLISHREQUEST']._serialized_end=338
  _globals['_PUBLISHRESPONSE']._serialized_start=340
  _globals['_PUBLISHRESPONSE']._serialized_end=423
  _globals['_EVENTBUSINGRESS']._serialized_start=425
  _globals['_EVENTBUSINGRESS']._serialized_end=522
# @@protoc_insertion_point(module_scope)
