# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from navigator_eventbus.ingress.proto import events_pb2 as navigator__eventbus_dot_ingress_dot_proto_dot_events__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in navigator_eventbus/ingress/proto/events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventBusIngressStub:
    """External ingress service for the navigator-eventbus event bus.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/parrot.events.v1.EventBusIngress/Publish',
                request_serializer=navigator__eventbus_dot_ingress_dot_proto_dot_events__pb2.PublishRequest.SerializeToString,
                response_deserializer=navigator__eventbus_dot_ingress_dot_proto_dot_events__pb2.PublishResponse.FromString,
                _registered_method=True)


class EventBusIngressServicer:
    """External ingress service for the navigator-eventbus event bus.
    """

    def Publish(self, request, context):
        """Publish one event; validation errors return a structured
        status="rejected" response and auth failures abort UNAUTHENTICATED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventBusIngressServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=navigator__eventbus_dot_ingress_dot_proto_dot_events__pb2.PublishRequest.FromString,
                    response_serializer=navigator__eventbus_dot_ingress_dot_proto_dot_events__pb2.PublishResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'parrot.events.v1.EventBusIngress', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('parrot.events.v1.EventBusIngress', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventBusIngress:
    """External ingress service for the navigator-eventbus event bus.
    """

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/parrot.events.v1.EventBusIngress/Publish',
            navigator__eventbus_dot_ingress_dot_proto_dot_events__pb2.PublishRequest.SerializeToString,
            navigator__eventbus_dot_ingress_dot_proto_dot_events__pb2.PublishResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
